### ISSUE TITLE
es2020 with yo-yoify

### ISSUE THREAD

**Issue by okdistribute** [yoshuawuyts/es2020#15]
hey @yoshuawuyts and @shama,

It seems like using `browserify -g yo-yoify -t es2020 app.js > bundle.js` is giving 

`app.js:56628 Uncaught TypeError: yo is not a function`

For now, we just turned off es2020, but it'd be nice to have it so we can use uglifyjs with yo-yo

/cc @laurengarcia

**Comment by yoshuawuyts** [comment]
uh oh, that doesn't sound good - I think it's because local transforms (`-t`) are run before global transforms (`-g`) and that messes up the `yo-yoify` bits. I think the solution here is to run:

``` sh
$ browserify -g yo-yoify -g es2020 app.js > bundle.js
```

Let me know if that works for you :sparkles:

**Comment by okdistribute** [comment]
@yoshuawuyts awesome!!! that worked!

**Comment by okdistribute** [comment]
thank you!

**Comment by laurengarcia** [comment]
!!! big ups, thanks
