### ISSUE TITLE
Object shorthand notation 

### ISSUE THREAD

**Issue by RamonGebben** [yoshuawuyts/es2020#4]
With shorthand notation for object composition you save the developer the effort of rewriting key value after the key when key and value have the same name. Instead of writing 

``` javascript
const myVar = "pizza"; 
const myObj = { myVar: myVar }; 
```

You would write 

``` javascript
const myVar = "pizza"; 
const myObj = { myVar };
```

Which would generate the same. 
I use this all the time in for instance redux action creators for the payload. 
By example: 

``` javascript
export function myAction(payload) { 
  return { type: 'my:action', payload } 
} 
```

EDIT: My phone screwed up markdown

**Comment by yoshuawuyts** [comment]
```js
const myVar = "pizza";
const myObj = { myVar: myVar, };
```
```js
const myVar = "pizza";
const myObj = { myVar, }
```
```js
export function myAction(payload) {
  return { type: 'my:action', payload, }
}
```

**Comment by yoshuawuyts** [comment]
Hmm, this one isn't for me I think - this is purely sugar, and I don't really see the point of using more types of creating objects than strictly necessary. The difference between `foo = { my : my }` and `foo = { my }` isn't large enough to matter imo

**Comment by yoshuawuyts** [comment]
Altough: https://github.com/yoshuawuyts/es2020/issues/1#issuecomment-222291965

``` js
function foo(bar, flop) {
  const { guid, baz, frog } = bar
  const { bing, bong, bam } = flop
  const ev = { type: 'did_the_thing', guid, baz, frog, bing, bong, bam }
  analytical_event(ev)
  return bar
}
```

**Comment by yoshuawuyts** [comment]
So we've decided against this for `es2020`, but if you want it anyway consider using https://github.com/ahdinosaur/es2040 :sparkles:

**Comment by markbrown4** [comment]
> The difference between foo = { my : my } and foo = { my } isn't large enough to matter imo

A 50% code reduction in literals is legitimate.

``` js
{ index: index, updates: updates, onChange: onChange }
// vs
{ index, updates, onChange }
```
- `fat arrows` - make inline functions cute-looking
- `object shorthand` - keep object literals DRY
