### ISSUE TITLE
Add source map support

### ISSUE THREAD

**Issue by bendrucker** [yoshuawuyts/es2020#5]
I'm happy to jump on a PR for this sometime this week. [Babelify](https://github.com/babel/babelify/blob/master/index.js) should be a good reference.

**Comment by yoshuawuyts** [comment]
Oh yeah, that'd be great! I'm giving you commit rights so you can merge when you see fit - thanks!

**Comment by yoshuawuyts** [comment]
Done - can now commit to npm and github. Added @ahdinosaur too :sparkles:

**Comment by yoshuawuyts** [comment]
neat, thanks! :sparkles:
