### ISSUE TITLE
errors when configured via `package.json`

### ISSUE THREAD

**Issue by ahdinosaur** [yoshuawuyts/es2020#6]
```
TypeError: Cannot read property 'debug' of undefined
    at DestroyableTransform.end [as _flush] (/.../node_modules/es2020/index.js:32:33)
```

because `browserify` is not passing `opts._flags` to the transforms if they are configured via `package.json`, which is an existing bug i've [raised](https://github.com/substack/node-browserify/issues/1463) and [fixed](https://github.com/substack/module-deps/pull/109), but has yet to be merged and published.

so maybe while we wait, we should default to something so it doesn't break?

**Comment by yoshuawuyts** [comment]
Lol, I even upvoted your fix - but yeah, let's fix it in the meantime. You should have commit rights - go ahead and merge if you like :sparkles:

**Comment by bendrucker** [comment]
Until module-deps is fixed I think it makes sense to default to source maps being on. babelify does it:

https://github.com/babel/babelify/blob/master/index.js#L42

**Comment by yoshuawuyts** [comment]
module deps was fixed, but seems we broke browserify in the process haha

**Comment by yoshuawuyts** [comment]
also +1 on source maps just being on (':

**Comment by ahdinosaur** [comment]
> module deps was fixed, but seems we broke browserify in the process haha

what do you mean?

**Comment by bendrucker** [comment]
https://github.com/substack/module-deps/pull/119

**Comment by ahdinosaur** [comment]
many thanks for the quick action @bendrucker. :smile: was added as a collaborator after https://github.com/substack/module-deps/pull/109 was merged, so merged and published your fix.

**Comment by bendrucker** [comment]
Cool, so this is now resolved with a fresh browserify install
