### ISSUE TITLE
Webpack loader

### ISSUE THREAD

**Issue by RamonGebben** [yoshuawuyts/es2020#9]
Currently you need a build process with relies on Browserify.
Would it be an idea to also include a webpack loader so that the end user can make a choice on what to use.

This might also increase the usage since a lot a companies are building on top of webpack and that way you could tome down the es6 magic in existing (webpack based) projects.

**Comment by yoshuawuyts** [comment]
If you want to create a `webpack` loader: go for it. It should work right now with https://github.com/hughsk/ify-loader though

**Comment by yoshuawuyts** [comment]
Also welcome to PR to this repo if you like: I reckon it should be simple enough. I'm an opponent of webpack in general, but I dislike most of ES6 more so... yeah, PR definitely welcome!

**Comment by RamonGebben** [comment]
Sure. Putting together the loader would not be that much effort, I will spend some time on it over the weekend. The only thing I'm not sure about is how to facilitate both webpack and browserify from the same package.

Do you have any ideas on how to approach this problem or is the only option to make another package called es2020-loader?

**Comment by yoshuawuyts** [comment]
webpack loader could sit at `es2020/webpack` or `es2020/loader` perhaps? :sparkles:

**Comment by RamonGebben** [comment]
You mean create an "Organization" account and put the repo there?

Then the most logical name for the package would be  `es2020-loader` since the convention is to name loaders like `something-loader`.

**Comment by yoshuawuyts** [comment]
Oh no - I dislike tiny orgs like that. If you're not going to PR it to this repo, I'd suggest creating it under your name and then we'll just link to it from here 😁

**Comment by yoshuawuyts** [comment]
Yeahhh, so I really can't be bothered writing this - if anyone wants to write a `webpack` loader, go for it! Happy to link to it from the docs :sparkles: Closing for now then
